import Head from "next/head";
import Footer from "components/Footer";
export default function AppLayout({ children }) {
  return (
    <>
      <Head>
        <title>Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
      <Footer />
      {/* <style jsx>{styles}</style> */}
      {/* <style jsx global> </style>*/}
    </>
  );
}
